kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: grafana-sa-dockercfg-4xf8s
  name: grafana-sa
  labels:
    app-management: grafana
    app.kubernetes.io/managed-by: grafana-operator
secrets:
  - name: grafana-sa-dockercfg-4xf8s
imagePullSecrets:
  - name: grafana-sa-dockercfg-4xf8s